# https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions

name: ci
on: [push]
jobs:
  build:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: . scripts/build.sh
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.8
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - run: terraform init
        working-directory: terraform
      - id: apply
        run: terraform apply -auto-approve
        working-directory: terraform
