# https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions

name: ci
on: [push]
jobs:
  build:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: |
          TARGET_DIR=terraform/input
          NODE_DIRS=("command-lambda" "interaction-lambda")
          for DIR in ${NODE_DIRS[@]}
          do
            echo "##################################   Creating archive for $DIR   ##################################"
            cd $DIR;
            npm install;
            npm run compile;
            cd ..;
            zip -j $TARGET_DIR/$DIR.zip $DIR/build/*
          done
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.8
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - run: terraform init
        working-directory: terraform
      - id: plan
        run: terraform plan
        working-directory: terraform
      - id: apply
        run: terraform apply -auto-approve
        working-directory: terraform
